version: '3'

services:
  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    restart: always

  web:
    build: .
    restart: always
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    env_file:
      - ./.env
    volumes:
      - .:/app
    command: >
      bash -c "python manage.py migrate &&
               python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"

  celery:
    build: .
    restart: always
    depends_on:
      - db
      - redis
    env_file:
      - ./.env
    volumes:
      - .:/app
    command: celery -A config worker -l info

  celery-beat:
    build: .
    restart: always
    depends_on:
      - db
      - redis
      - celery
    env_file:
      - ./.env
    volumes:
      - .:/app
    command: celery -A config beat -l info

volumes:
  postgres_data: