# Generated by Django 4.2.1 on 2025-03-27 14:55

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Название")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "periodicity",
                    models.CharField(
                        choices=[("daily", "Ежедневно"), ("weekly", "Еженедельно")],
                        default="daily",
                        max_length=10,
                        verbose_name="Периодичность",
                    ),
                ),
                ("time_to_complete", models.TimeField(verbose_name="Время выполнения")),
                (
                    "estimated_duration",
                    models.PositiveIntegerField(
                        help_text="Макс. 120 минут",
                        validators=[django.core.validators.MaxValueValidator(120)],
                        verbose_name="Оценочная продолжительность (мин)",
                    ),
                ),
                (
                    "reward",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Вознаграждение"
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=False, verbose_name="Публичная привычка"
                    ),
                ),
                (
                    "is_pleasant",
                    models.BooleanField(
                        default=False, verbose_name="Приятная привычка"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "related_habit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="linked_habits",
                        to="habits.habit",
                        verbose_name="Связанная привычка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Привычка",
                "verbose_name_plural": "Привычки",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="HabitCompletion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_completed",
                    models.DateField(auto_now_add=True, verbose_name="Дата выполнения"),
                ),
                (
                    "time_completed",
                    models.TimeField(
                        auto_now_add=True, verbose_name="Время выполнения"
                    ),
                ),
                (
                    "is_successful",
                    models.BooleanField(default=True, verbose_name="Успешно выполнено"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Заметки")),
                (
                    "habit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="completions",
                        to="habits.habit",
                        verbose_name="Привычка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Выполнение привычки",
                "verbose_name_plural": "Выполнения привычек",
                "ordering": ["-date_completed", "-time_completed"],
            },
        ),
    ]
