# Generated by Django 4.2.1 on 2025-03-27 19:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import habits.validators


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("habits", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="habit",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Привычка",
                "verbose_name_plural": "Привычки",
            },
        ),
        migrations.AlterModelOptions(
            name="habitcompletion",
            options={
                "ordering": ["-completed_at"],
                "verbose_name": "Выполнение привычки",
                "verbose_name_plural": "Выполнения привычек",
            },
        ),
        migrations.AlterUniqueTogether(
            name="habitcompletion",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="habit",
            name="action",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Действие"
            ),
        ),
        migrations.AddField(
            model_name="habit",
            name="place",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Место"
            ),
        ),
        migrations.AddField(
            model_name="habitcompletion",
            name="completed_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Время выполнения"
            ),
        ),
        migrations.AddField(
            model_name="habitcompletion",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="habit_completions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
        ),
        migrations.AlterField(
            model_name="habit",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="habit",
            name="estimated_duration",
            field=models.PositiveIntegerField(
                default=60,
                help_text="Сколько времени предположительно займет выполнение",
                validators=[habits.validators.validate_execution_time],
                verbose_name="Расчетное время выполнения (в секундах)",
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="is_pleasant",
            field=models.BooleanField(
                default=False,
                help_text="Отметьте, если это приятная привычка",
                verbose_name="Приятная привычка",
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="is_public",
            field=models.BooleanField(
                default=False,
                help_text="Отметьте, если привычка будет доступна всем пользователям",
                verbose_name="Публичная привычка",
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="habit",
            name="periodicity",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Как часто нужно выполнять привычку (в днях)",
                validators=[habits.validators.validate_periodicity],
                verbose_name="Периодичность (в днях)",
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="related_habit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="related_habits",
                to="habits.habit",
                verbose_name="Связанная привычка",
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="reward",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Вознаграждение"
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
        ),
        migrations.AlterField(
            model_name="habit",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="habits",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="habitcompletion",
            name="habit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="completions",
                to="habits.habit",
            ),
        ),
        migrations.RemoveField(
            model_name="habitcompletion",
            name="date_completed",
        ),
        migrations.RemoveField(
            model_name="habitcompletion",
            name="is_successful",
        ),
        migrations.RemoveField(
            model_name="habitcompletion",
            name="notes",
        ),
        migrations.RemoveField(
            model_name="habitcompletion",
            name="time_completed",
        ),
    ]
