# Generated by Django 4.2.1 on 2025-03-30 17:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("habits", "0004_telegramprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="habitcompletion",
            name="is_successful",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="habitcompletion",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="habitcompletion",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="habit_completions",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
