# Generated by Django 4.2.1 on 2025-03-31 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0005_habitcompletion_is_successful_habitcompletion_notes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="habit",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Активна"),
        ),
    ]
