# Generated by Django 4.2.1 on 2025-03-27 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NotificationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Время отправки"
                    ),
                ),
                ("message", models.TextField(verbose_name="Текст сообщения")),
                (
                    "is_delivered",
                    models.BooleanField(default=False, verbose_name="Доставлено"),
                ),
            ],
            options={
                "verbose_name": "Лог уведомлений",
                "verbose_name_plural": "Логи уведомлений",
                "ordering": ["-sent_at"],
            },
        ),
        migrations.CreateModel(
            name="TelegramState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "telegram_id",
                    models.CharField(max_length=50, verbose_name="ID в Telegram"),
                ),
                (
                    "state",
                    models.CharField(
                        default="start",
                        max_length=100,
                        verbose_name="Состояние диалога",
                    ),
                ),
                (
                    "context",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Контекст диалога"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
            ],
            options={
                "verbose_name": "Состояние в Telegram",
                "verbose_name_plural": "Состояния в Telegram",
            },
        ),
    ]
