# Generated by Django 4.2 on 2025-04-26 18:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0006_habit_is_active"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("telegram_bot", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Achievement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Название")),
                ("description", models.TextField(verbose_name="Описание")),
                (
                    "image",
                    models.CharField(max_length=50, verbose_name="Эмодзи/Иконка"),
                ),
                (
                    "condition_type",
                    models.CharField(max_length=50, verbose_name="Тип условия"),
                ),
                (
                    "condition_value",
                    models.IntegerField(verbose_name="Значение условия"),
                ),
            ],
            options={
                "verbose_name": "Достижение",
                "verbose_name_plural": "Достижения",
            },
        ),
        migrations.AlterModelOptions(
            name="notificationlog",
            options={
                "verbose_name": "Лог уведомлений",
                "verbose_name_plural": "Логи уведомлений",
            },
        ),
        migrations.AlterModelOptions(
            name="telegramstate",
            options={
                "verbose_name": "Состояние Telegram",
                "verbose_name_plural": "Состояния Telegram",
            },
        ),
        migrations.AddField(
            model_name="notificationlog",
            name="response_time",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Время ответа"
            ),
        ),
        migrations.AddField(
            model_name="notificationlog",
            name="user_response",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Ответ пользователя"
            ),
        ),
        migrations.AlterField(
            model_name="notificationlog",
            name="habit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="habits.habit",
                verbose_name="Привычка",
            ),
        ),
        migrations.AlterField(
            model_name="telegramstate",
            name="telegram_id",
            field=models.BigIntegerField(unique=True, verbose_name="Telegram ID"),
        ),
        migrations.CreateModel(
            name="UserAchievement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_earned",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата получения"
                    ),
                ),
                (
                    "achievement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="telegram_bot.achievement",
                        verbose_name="Достижение",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="achievements",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Достижение пользователя",
                "verbose_name_plural": "Достижения пользователей",
                "unique_together": {("user", "achievement")},
            },
        ),
    ]
